backend:
  name: turbo-github
  turbo_site_id: d6760930-3fc4-478c-b0d7-1bfedbcdaf81
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Website"
    files:
      - file: "content/site.yml"
        label: "Website Information"
        name: "site"
        fields:

          - label: "Business Name"
            name: "business_name"
            widget: "string"

          - label: "Phone"
            name: "phone"
            widget: "string"

          - label: "Email"
            name: "email"
            widget: "string"

          - label: "Address"
            name: "address"
            widget: "string"

          - label: "Hours"
            name: "hours"
            widget: "text"

          - label: "About / Description"
            name: "description"
            widget: "text"

          - label: "Interior Detail Name"
            name: "interior_name"
            widget: "string"

          - label: "Interior Detail Description"
            name: "interior_description"
            widget: "text"

          - label: "Interior Detail Price"
            name: "interior_price"
            widget: "number"

          - label: "Exterior Detail Name"
            name: "exterior_name"
            widget: "string"

          - label: "Exterior Detail Description"
            name: "exterior_description"
            widget: "text"

          - label: "Exterior Detail Price"
            name: "exterior_price"
            widget: "number"

          - label: "Full Detail Name"
            name: "full_name"
            widget: "string"

          - label: "Full Detail Description"
            name: "full_description"
            widget: "text"

          - label: "Full Detail Price"
            name: "full_price"
            widget: "number"
