backend:
  name: turbo-github
  turbo_site_id: d6760930-3fc4-478c-b0d7-1bfedbcdaf81
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Website"
    files:
      - file: "content/site.yml"
        label: "Website Information"
        name: "site"
        fields:
          - label: "Business Name"
            name: "business_name"
            widget: "string"
          - label: "Interior Detail Price"
            name: "interior_price"
            widget: "number"
          - label: "Exterior Detail Price"
            name: "exterior_price"
            widget: "number"
          - label: "Full Detail Price"
            name: "full_price"
            widget: "number"
